### ISSUE TITLE
vBulletin Entegre

### ISSUE THREAD

**Issue by yilmaztv** [alicangnll/phpwaf-phanalyzer#3]
Merhaba bu vbulletin 4 de entegre olurmu?

**Comment by yilmaztv** [comment]
Can't create database 'firewall'; database exists

bu hatayı alıyorum

**Comment by alicangnll** [comment]
Merhaba,

Zaten veritaban oluşturulmuş. Kurulumda index.php?git=install2 kısmına atlayabilirsiniz. vBullettin 4 entegrasyonu henüz denenmedi fakat kurallar buna göre düzenlendiğinde çalışacaktır.

Geç cevap için üzgünüm.
Geri bildiriminiz için teşekkür ederim.


Sorularınız için github@alicangonullu.org mail gönderebilirsiniz

**Comment by alicangnll** [comment]
İzninizle sorununuzun bildirisini kapatıyorum.
